name: aic
services:
  eval:
    image: ghcr.io/intrinsic-dev/aic/aic_eval
    # image: my-eval:v1
    build:
      dockerfile: docker/aic_eval/Dockerfile
      context: ..
    command: gazebo_gui:=true launch_rviz:=true ground_truth:=true start_aic_engine:=true shutdown_on_aic_engine_exit:=true
    gpus: all
    networks:
      - default
    environment:
      DISPLAY: $DISPLAY
      AIC_EVAL_PASSWD: CHANGE_IN_PROD
      AIC_MODEL_PASSWD: CHANGE_IN_PROD
      # AIC_ENABLE_ACL: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/home/leap/.Xauthority:rw
      - $HOME/.Xauthority:/root/.Xauthority:rw

  model:
    image: my-solution:v1
    build:
      dockerfile: docker/aic_model/Dockerfile
      context: ..
    command: --ros-args -p use_sim_time:=true -p policy:=aic_example_policies.ros.CheatCode
    gpus: all
    networks:
      - default
    environment:
      RMW_IMPLEMENTATION: rmw_zenoh_cpp
      ZENOH_ROUTER_CHECK_ATTEMPTS: -1
      AIC_ROUTER_ADDR: eval:7447
      AIC_MODEL_PASSWD: CHANGE_IN_PROD
      # AIC_ENABLE_ACL: true
networks:
  default:
    internal: true
